export interface SiteInspection {
  url: string;
  finalUrl: string;
  domain: string;
  title: string | null;
  description: string | null;
  siteName: string | null;
  ogImage: string | null;
  themeColor: string | null;
  headings: string[];
  ctas: string[];
  keywords: string[];
}

export interface PaletteSwatch {
  name: string;
  hex: string;
}

export interface BrandPreview {
  url: string;
  domain: string;
  companyName: string;
  tagline: string;
  summary: string;
  audience: string[];
  voice: string[];
  valueProps: string[];
  palette: PaletteSwatch[];
  keywords: string[];
  ogImage: string | null;
  /** "heuristic" when derived locally; "vertex" when generated by the AI model. */
  source: "heuristic" | "vertex";
}

export interface StrategyAngle {
  title: string;
  hook: string;
  audience: string;
}

export interface AdStrategy {
  objective: string;
  angles: StrategyAngle[];
  audiences: string[];
  dailyBudget: number;
  currency: string;
  testingPlan: string;
}

export interface CreativeConcept {
  name: string;
  angle: string;
  format: string;
  primaryText: string;
  headline: string;
  description: string;
  cta: string;
}

export interface CampaignAdSet {
  name: string;
  audience: string;
  optimization: string;
  ads: number;
}

export interface CampaignPlan {
  name: string;
  objective: string;
  status: "draft";
  dailyBudget: number;
  currency: string;
  adSets: CampaignAdSet[];
}

/** The full, automatically-generated advertising plan for a store. */
export interface AdPlan {
  brand: BrandPreview;
  strategy: AdStrategy;
  creatives: CreativeConcept[];
  campaign: CampaignPlan;
}
