export interface SiteInspection {
  url: string;
  finalUrl: string;
  domain: string;
  title: string | null;
  description: string | null;
  siteName: string | null;
  ogImage: string | null;
  themeColor: string | null;
  headings: string[];
  ctas: string[];
  keywords: string[];
}

export interface PaletteSwatch {
  name: string;
  hex: string;
}

export interface BrandPreview {
  url: string;
  domain: string;
  companyName: string;
  tagline: string;
  summary: string;
  audience: string[];
  voice: string[];
  valueProps: string[];
  palette: PaletteSwatch[];
  keywords: string[];
  ogImage: string | null;
  /** "heuristic" when derived locally; "vertex" when generated by the AI model. */
  source: "heuristic" | "vertex";
}
